services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - default

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  #     ME_CONFIG_BASICAUTH: false
  #   networks:
  #     - default
  #   depends_on:
  #     - mongo

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - MONGO_DB_URL=mongodb://mongo:27017/
    networks:
      - default
    # For production
    # command: npm start

    # For development
    volumes:
      - .:/app
    command: npm run dev


volumes:
  mongodb_data:

networks:
  default:
    driver: bridge

