services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: test-user
      MONGO_INITDB_ROOT_PASSWORD: test-password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - default

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: test-user
      ME_CONFIG_MONGODB_ADMINPASSWORD: test-password
      ME_CONFIG_MONGODB_URL: mongodb://test-user:test-password@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      # Change here in case of using other mongodb service, such as MongoDB Atlas.
      - MONGO_DB_URL=mongodb://mongo:27017/

      # For using with mongodb service. 
      # Comment below if you're passing credentials through MONGO_DB_URL.
      - MONGO_DB_NAME=test
      - MONGO_DB_USER=test-user
      - MONGO_DB_PASSWORD=test-password
    networks:
      - default
    depends_on:
      - mongo

volumes:
  mongodb_data:

networks:
  default:
    driver: bridge

