name: Cypress

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-24.04
      
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user 1001
  
    services:
      mongodb:
        image: mongo:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        ports:
          - 27017:27017

    env:
      MONGO_DB_URL: mongodb://mongodb:27017/
      MONGO_DB_NAME: test
      MONGO_DB_USER: root
      MONGO_DB_PASSWORD: example
      EPISODES_FILES_PATH: /app/episodes
      USE_TEST_DB: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
        build: npm run build
        start: npm start
        browser: chrome
